[ {
  "category" : "Front Ends",
  "name" : "taskwarrior-pomodoro",
  "description" : "taskwarrior-pomodoro is a simple application allowing you to use Pomodoro techniques with Taskwarrior on OSX. \n<a href=\"https://github.com/coddingtonbear/taskwarrior-pomodoro\"> <img alt=\"taskwarrior-pomodoro\" src=\"https://camo.githubusercontent.com/e88877839afe5bc08e29a1d632257397bc4cc677/687474703a2f2f636f6464696e67746f6e626561722d7075626c69632e73332e616d617a6f6e6177732e636f6d2f6769746875622f7461736b77617272696f722d706f6d6f646f726f2f73637265656e73686f742e706e67\"> </a> \n<small><a href=\"https://github.com/coddingtonbear/taskwarrior-pomodoro\"></a></small>\n<a href=\"https://github.com/coddingtonbear/taskwarrior-pomodoro\"> </a>",
  "url" : "https://github.com/coddingtonbear/taskwarrior-pomodoro",
  "url_src" : null,
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Adam Coddington" ],
  "theme" : [ "OSX" ],
  "compatibility" : "2.0+",
  "obsolete" : false,
  "verified" : null,
  "last_update" : "2015-12-07"
}, {
  "category" : "Front Ends",
  "name" : "taskswamp",
  "description" : "taskswamp is a simple script to launch an xterm containing a tmux containing multiple task reports, and have them refreshed at a keypress.",
  "url" : "https://github.com/danielshahaf/taskswamp/",
  "url_src" : "https://github.com/danielshahaf/taskswamp/",
  "license" : "Apache 2.0",
  "language" : [ ],
  "author" : [ "Daniel Shahaf" ],
  "theme" : [ ],
  "compatibility" : "any",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-08-12"
}, {
  "category" : "Front Ends",
  "name" : "vim-taskwarrior",
  "description" : "A full-featured, interactive interface for taskwarrior using vim",
  "url" : "http://github.com/farseer90718/vim-taskwarrior",
  "url_src" : "http://github.com/farseer90718/vim-taskwarrior",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "zc he" ],
  "theme" : [ "Vim" ],
  "compatibility" : "2.2.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-04-29"
}, {
  "category" : "Front Ends",
  "name" : "Vit",
  "description" : "Vit is a full-screen terminal interface to Taskwarrior with Vim key bindings.",
  "url" : "http://tasktools.org/projects/vit.html",
  "url_src" : "https://git.tasktools.org/scm/ex/vit.git",
  "license" : "GPLv3",
  "language" : [ ],
  "author" : [ "Scott Kostyshak", "Steve Rader" ],
  "theme" : [ "Vim" ],
  "compatibility" : "2.0.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-03-08"
}, {
  "category" : "Front Ends",
  "name" : "Inthe.AM",
  "description" : "A modern web frontend for accessing your tasks",
  "url" : "http://inthe.am/",
  "url_src" : null,
  "license" : "AGPLv3",
  "language" : [ ],
  "author" : [ "Adam Coddington & others" ],
  "theme" : [ "Web" ],
  "compatibility" : "2.3.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : null
}, {
  "category" : "Front Ends",
  "name" : "tasksh",
  "description" : "Tasksh is an interactive shell for taskwarrior \n<small> <a href=\"http://taskwarrior.org/download/tasksh-latest.tar.gz\">Tarball</a> SHA1 5fb9209ec1cafbbde4aa165f41ffb3aeba6faca8 </small>",
  "url" : "https://git.tasktools.org/projects/EX/repos/tasksh",
  "url_src" : "https://git.tasktools.org/projects/EX/repos/tasksh",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "GBF" ],
  "theme" : [ ],
  "compatibility" : "2.4.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2014-12-21"
}, {
  "category" : "Front Ends",
  "name" : "ptask",
  "description" : "ptask is a GTK+ graphical user interface for managing tasks.",
  "url" : "http://wpitchoune.net/ptask",
  "url_src" : "http://wpitchoune.net/ptask/files",
  "license" : "GPLv2",
  "language" : [ ],
  "author" : [ "Jean-Philippe Orsini" ],
  "theme" : [ "GUI" ],
  "compatibility" : "2.0.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2014-11-22"
}, {
  "category" : "Front Ends",
  "name" : "tchart",
  "description" : "Python reporting and front-end for Taskwarrior. A GANTT chart style front end Taskwarrior. Tchart allows for rapid selection and modification of tasks, while the GANTT type report enables a rapid visual overview of tasks based on their due dates.",
  "url" : "https://github.com/grovesteyn/tchart.git",
  "url_src" : "https://github.com/grovesteyn/tchart",
  "license" : "GPLv2",
  "language" : [ "Python" ],
  "author" : [ "Grové Steyn" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-10-31"
}, {
  "category" : "Front Ends",
  "name" : "Taskwarrior-web",
  "description" : "Taskwarrior-web is a Sinatra-based web front end for Taskwarrior.",
  "url" : "https://github.com/theunraveler/taskwarrior-web",
  "url_src" : "https://github.com/theunraveler/taskwarrior-web",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Jake Bell" ],
  "theme" : [ "Web" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-09-18"
}, {
  "category" : "Services",
  "name" : "FreeCinc",
  "description" : "Don't want to manage your own Taskserver? FreeCinc is a hosted implementation of Taskserver, where you can download a set of uniquely-generated credentials and start syncing for free.",
  "url" : "http://freecinc.com",
  "url_src" : null,
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Jack Desert" ],
  "theme" : [ ],
  "compatibility" : "2.3.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : null
}, {
  "category" : "Libraries",
  "name" : "tasklib",
  "description" : "Python library for interacting with Taskwarrior data",
  "url" : "http://tasklib.readthedocs.org/en/latest/",
  "url_src" : "https://github.com/tbabej/tasklib",
  "license" : "BSD 3 clause",
  "language" : [ "Python" ],
  "author" : [ "Rob Golding", "Tomas Babej" ],
  "theme" : [ ],
  "compatibility" : "2.1.x - 2.4.x",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-08-09"
}, {
  "category" : "Libraries",
  "name" : "Taskwarrior PHP lib",
  "description" : "PHP Taskwarrior library, used in \n<a href=\"https://github.com/DavidBadura/doThings\">doThings</a>.",
  "url" : "https://github.com/DavidBadura/Taskwarrior",
  "url_src" : "https://github.com/DavidBadura/Taskwarrior",
  "license" : "MIT",
  "language" : [ "PHP" ],
  "author" : [ "David Badura" ],
  "theme" : [ ],
  "compatibility" : "2.4.4",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-08-01"
}, {
  "category" : "Libraries",
  "name" : "taskc",
  "description" : "Python taskd client library",
  "url" : "https://pypi.python.org/pypi/taskc",
  "url_src" : "https://github.com/jrabbit/taskd-client-py",
  "license" : "LGPLv3",
  "language" : [ "Python" ],
  "author" : [ "Jack Laxson" ],
  "theme" : [ ],
  "compatibility" : "taskd 1.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-06-30"
}, {
  "category" : "Libraries",
  "name" : "rtasklib",
  "description" : "Ruby Taskwarrior bindings.",
  "url" : "https://github.com/dropofwill/rtasklib",
  "url_src" : "https://github.com/dropofwill/rtasklib",
  "license" : "MiT",
  "language" : [ ],
  "author" : [ "Will Paul" ],
  "theme" : [ ],
  "compatibility" : "2.4.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-05-18"
}, {
  "category" : "Libraries",
  "name" : "taskw",
  "description" : "Python bindings for your taskwarrior database",
  "url" : "https://pypi.python.org/pypi/taskw",
  "url_src" : "https://github.com/ralphbean/taskw",
  "license" : "GPLv3+",
  "language" : [ "Python" ],
  "author" : [ "Ralph Bean and contributors" ],
  "theme" : [ ],
  "compatibility" : "2.2.x - 2.4.x",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-04-21"
}, {
  "category" : "Hook Scripts",
  "name" : "Time Tracking Hook",
  "description" : "Robust implementation of a time-tracking hook script, supporting non-UTF8 JSON.",
  "url" : "/download/on-modify.timetrack.pl",
  "url_src" : "/download/on-modify.timetrack.pl",
  "license" : "GPL",
  "language" : [ ],
  "author" : [ "Klaus Ethgen" ],
  "theme" : [ ],
  "compatibility" : "2.4.1+",
  "obsolete" : false,
  "verified" : "2016-01-11",
  "last_update" : "2016-01-11"
}, {
  "category" : "Hook Scripts",
  "name" : "Ledger Time Tracking Hook",
  "description" : "Writes time spent on tasks (\"task start\", \"task stop\") into a timelog formatted file. Example \n<a href=\"http://www.ledger-cli.org/\">ledger CLI</a> reports:\"ledger -f timetrack.ledger print\"\"ledger -f timetrack.ledger register\"",
  "url" : "https://gist.github.com/wbsch/d977b0ac29aa1dfa4437",
  "url_src" : "https://gist.github.com/wbsch/d977b0ac29aa1dfa4437",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Wim Schuermann", "David J Patrick" ],
  "theme" : [ "Ledger" ],
  "compatibility" : "2.4.1+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-07-01"
}, {
  "category" : "Hook Scripts",
  "name" : "Relative Recurring Tasks Hook",
  "description" : "A hook providing relative recurring tasks with due date some period after completing the current task.",
  "url" : "https://github.com/JensErat/task-relative-recur",
  "url_src" : "https://github.com/JensErat/task-relative-recur",
  "license" : "MIT License",
  "language" : [ ],
  "author" : [ "Jens Erat" ],
  "theme" : [ ],
  "compatibility" : "2.4.2+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-06-15"
}, {
  "category" : "Hook Scripts",
  "name" : "Default Date Time Hook",
  "description" : "A simple Taskwarrior hook that allows setting other default time for dates than 00:00:00.",
  "url" : "https://github.com/tbabej/taskwarrior-default-date-time-hook",
  "url_src" : "https://github.com/tbabej/taskwarrior-default-date-time-hook",
  "license" : "MIT License",
  "language" : [ ],
  "author" : [ "Tomas Babej" ],
  "theme" : [ ],
  "compatibility" : "2.4.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-06-01"
}, {
  "category" : "Hook Scripts",
  "name" : "Use Git to track changes Hook",
  "description" : "Proof of concept for a Taskwarrior on-exit hook that manages a git repository in ~/.task",
  "url" : "https://gist.github.com/wbsch/fe5d0f392657fdfa6fe4",
  "url_src" : "https://gist.github.com/wbsch/fe5d0f392657fdfa6fe4",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Wim Schuermann" ],
  "theme" : [ ],
  "compatibility" : "2.4.2+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-06-01"
}, {
  "category" : "Hook Scripts",
  "name" : "Shift All Recurrence Hook",
  "description" : "Have your wait, scheduled and until attributes shifted by the recurrence span of recurrent tasks the same way that due attribute is shifted. Don't let your periodic tasks clutter up your task list any longer.",
  "url" : "https://github.com/tbabej/taskwarrior-shift-all-recurrence-hook",
  "url_src" : "https://github.com/tbabej/taskwarrior-shift-all-recurrence-hook",
  "license" : "MIT License",
  "language" : [ ],
  "author" : [ "Tomas Babej" ],
  "theme" : [ ],
  "compatibility" : "2.4.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-05-27"
}, {
  "category" : "Hook Scripts",
  "name" : "Time Tracking Hook",
  "description" : "A simple Taskwarrior hook allowing one to track total time spent on a task.",
  "url" : "https://github.com/kostajh/taskwarrior-time-tracking-hook",
  "url_src" : "https://github.com/kostajh/taskwarrior-time-tracking-hook",
  "license" : "MIT License",
  "language" : [ ],
  "author" : [ "Kosta Harlan", "Adam Coddington" ],
  "theme" : [ ],
  "compatibility" : "2.4.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-04-20"
}, {
  "category" : "Hook Scripts",
  "name" : "\"blocks:\" Attribute Hook",
  "description" : "Adds a \"blocks:\" pseudo-attribute for adding/modifying tasks. \"blocks:\" is the opposite of \"depends:\".",
  "url" : "https://gist.github.com/wbsch/a2f7264c6302918dfb30",
  "url_src" : "https://gist.github.com/wbsch/a2f7264c6302918dfb30",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Wim Schuermann" ],
  "theme" : [ ],
  "compatibility" : "2.4.2+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-04-01"
}, {
  "category" : "Extensions",
  "name" : "estact",
  "description" : "Velocity (Estimated vs actual time) graph. Plots a velocity graphic for tasks not older than six months:",
  "url" : "https://github.com/envolyse/estact",
  "url_src" : "https://github.com/envolyse/estact",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Vladislav Bykov" ],
  "theme" : [ ],
  "compatibility" : "2.1.0+",
  "obsolete" : false,
  "verified" : "2016-03-19",
  "last_update" : "2016-03-19"
}, {
  "category" : "Extensions",
  "name" : "taskwiki",
  "description" : "Taskwiki is a Vim plugin to sync Taskwarrior tasks to simple freeform text files and vice versa. Keep your project notes and tasks together!",
  "url" : "https://github.com/tbabej/taskwiki",
  "url_src" : "https://github.com/tbabej/taskwiki",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Tomas Babej" ],
  "theme" : [ "Vim" ],
  "compatibility" : "2.1.x - 2.4.x",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-08-15"
}, {
  "category" : "Extensions",
  "name" : "header2task",
  "description" : "Script to manipulate taskwarrior tasks when passed a raw email via stdin. Annotating the task with the email's message-id, from, and subject headers.",
  "url" : "https://github.com/derekschrock/header2task",
  "url_src" : "https://github.com/derekschrock/header2task",
  "license" : "Simplified BSD",
  "language" : [ ],
  "author" : [ "Derek Schrock" ],
  "theme" : [ "Mail" ],
  "compatibility" : "2.3.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-08-15"
}, {
  "category" : "Extensions",
  "name" : "taskgit",
  "description" : "taskgit is a simple wrapper script that automatically tracks your TASKDIR folder in git, making commits every time data changes.",
  "url" : "https://gist.github.com/Unode/9366218",
  "url_src" : "https://gist.github.com/Unode/9366218",
  "license" : "GPLv3",
  "language" : [ ],
  "author" : [ "Renato Alves" ],
  "theme" : [ ],
  "compatibility" : "All versions",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-08-12"
}, {
  "category" : "Extensions",
  "name" : "meteor-taskwarrior",
  "description" : "taskwarrior client in meteor.js",
  "url" : "https://github.com/venturecommunism/meteor-taskwarrior",
  "url_src" : "https://github.com/venturecommunism/meteor-taskwarrior",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "venturecommunism" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-08-12"
}, {
  "category" : "Extensions",
  "name" : "bugwarrior",
  "description" : "bugwarrior - Pull tickets from github, bitbucket, bugzilla, jira, trac, and others into taskwarrior",
  "url" : "https://github.com/ralphbean/bugwarrior",
  "url_src" : "https://github.com/ralphbean/bugwarrior",
  "license" : "GPLv3",
  "language" : [ ],
  "author" : [ "Ralph Bean" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-07-29"
}, {
  "category" : "Extensions",
  "name" : "Import/Export Format Converters",
  "description" : "These are the format conversion scripts formerly included with Taskwarrior releases, but now moved online. \n<small><a>export-csv.pl</a></small> \n<small><a>export-html.pl</a></small> \n<small><a>export-ical.pl</a></small> \n<small><a>export-sql.py</a></small> \n<small><a>export-tsv.pl</a></small> \n<small><a>export-xml.pl</a></small> \n<small><a>export-xml.py</a></small> \n<small><a>export-xml.rb</a></small> \n<small><a>export-yad.pl</a></small> \n<small><a>export-yaml.pl</a></small> \n<small><a>import-todo.sh.pl</a></small> \n<small><a>import-yaml.pl</a></small>",
  "url" : "",
  "url_src" : null,
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Taskwarrior Team" ],
  "theme" : [ ],
  "compatibility" : "2.0.0+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-07-29"
}, {
  "category" : "Extensions",
  "name" : "tasknc",
  "description" : "tasknc is a ncurses wrapper for task warrior written in C. It aims to provide an interface like the excellent ncurses programs mutt and ncmpcpp",
  "url" : "https://github.com/lharding/tasknc",
  "url_src" : "https://github.com/lharding/tasknc",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Leander Harding" ],
  "theme" : [ ],
  "compatibility" : "2.2.0",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-07-28"
}, {
  "category" : "Extensions",
  "name" : "dashborg",
  "description" : "Curses-based Taskwarrior dashboard for your pocket computer.",
  "url" : "https://github.com/lharding/dashborg",
  "url_src" : "https://github.com/lharding/dashborg",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Leander Harding" ],
  "theme" : [ ],
  "compatibility" : "2.2.0",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-07-28"
}, {
  "category" : "Extensions",
  "name" : "taskwarrior-notifications",
  "description" : "A collection of ways to alert me/bring attention to my task list because I'm easily distracted and need help focusing... what was I doing again? Ohhh, a new podcast...",
  "url" : "https://github.com/flickerfly/taskwarrior-notifications",
  "url_src" : "https://github.com/flickerfly/taskwarrior-notifications",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Josiah Ritchie" ],
  "theme" : [ ],
  "compatibility" : "1.9.4",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-07-27"
}, {
  "category" : "Extensions",
  "name" : "task-indicator",
  "description" : "A simple indicator application that helps do simple things with Taskwarrior, like finding and adding tasks, starting and stopping them, track current activity time, etc.",
  "url" : "http://umonkey.net/projects/task-indicator/index.en.html",
  "url_src" : "http://umonkey.net/projects/task-indicator/index.en.html",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Justin Forest" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-06-19"
}, {
  "category" : "Extensions",
  "name" : "trev",
  "description" : "A mini-shell focusing on taskwarrior reviewing",
  "url" : "https://github.com/nocejo/trev",
  "url_src" : "https://github.com/nocejo/trev",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Fidel Mato" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-05-25"
}, {
  "category" : "Extensions",
  "name" : "Pinboard HTML",
  "description" : "Inspired by export-html.py, this is a modified version that prints the task list by project into an HTML. \n<small><a href=\"http://www.taskextras.org/boards/1/topics/2286\">Screen Shot</a></small>",
  "url" : "https://github.com/vsbabu/pinboard/tree/master/utils",
  "url_src" : "https://github.com/vsbabu/pinboard/tree/master/utils",
  "license" : "Free",
  "language" : [ ],
  "author" : [ "Satheesh Vattekkat" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-05-05"
}, {
  "category" : "Extensions",
  "name" : "tasktime",
  "description" : "Calculate and print spent time for a project from taskwarrior",
  "url" : "https://github.com/svenhertle/tasktime",
  "url_src" : "https://github.com/svenhertle/tasktime",
  "license" : "own",
  "language" : [ ],
  "author" : [ "Sven Hertle" ],
  "theme" : [ ],
  "compatibility" : "2.1.2",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2015-03-01"
}, {
  "category" : "Extensions",
  "name" : "gtw",
  "description" : "Git wrapper Gtw keeps commits in a separate (configurable) branch in a git main repository. Gtw passes all commands directly through to taskwarrior, for maximum compatibility.",
  "url" : "https://github.com/hoxu/gtw",
  "url_src" : "https://github.com/hoxu/gtw",
  "license" : "GPLv3",
  "language" : [ ],
  "author" : [ "Heikki Hokkanen" ],
  "theme" : [ ],
  "compatibility" : "All",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2014-12-06"
}, {
  "category" : "Extensions",
  "name" : "twmail",
  "description" : "<code>twmail</code> allows you to mail new tasks to your Taskwarrior inbox",
  "url" : "https://github.com/nerab/TaskWarriorMail",
  "url_src" : "https://github.com/nerab/TaskWarriorMail",
  "license" : "MIT License",
  "language" : [ ],
  "author" : [ "Nicholas E. Rabenau" ],
  "theme" : [ "Mail" ],
  "compatibility" : "2.1.0",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2014-11-16"
}, {
  "category" : "Extensions",
  "name" : "taskgv",
  "description" : "Generates a pretty, directed graph of Taskwarrior projects, tags, and tasks.",
  "url" : "https://github.com/shushcat/taskgv",
  "url_src" : "https://github.com/shushcat/taskgv",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "John O Brickley" ],
  "theme" : [ ],
  "compatibility" : "2.0.0",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2014-09-07"
}, {
  "category" : "Extensions",
  "name" : "task-anon",
  "description" : "Anonymizes project names, task descriptions and annotations with md5 hashes that include a salt to provide a modicum of security. Tags are not anonymized (how would users indicate the problem tasks otherwise?). Anonymizing data is for helping developers diagnose data-specific problems with Taskwarrior.",
  "url" : "https://git.tasktools.org/projects/ST/repos/tw.org/commits/eb41773ce401bb6f3f4e145b237450074f5be8c5",
  "url_src" : "https://git.tasktools.org/projects/ST/repos/tw.org/commits/eb41773ce401bb6f3f4e145b237450074f5be8c5",
  "license" : "GPLv2",
  "language" : [ ],
  "author" : [ "Cory Donnelly", "Johannes Schlatow" ],
  "theme" : [ ],
  "compatibility" : "All",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2014-07-10"
}, {
  "category" : "Extensions",
  "name" : "ac-task-php",
  "description" : "ActiveCollab and Taskwarrior integration",
  "url" : "https://github.com/kostajh/ac-task-php",
  "url_src" : "https://github.com/kostajh/ac-task-php",
  "license" : "GPLv2",
  "language" : [ ],
  "author" : [ "Kosta Harlan" ],
  "theme" : [ ],
  "compatibility" : "2.2.0",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2014-02-19"
}, {
  "category" : "Extensions",
  "name" : "taskopen",
  "description" : "taskopen is used for opening files that are added with their paths as a task annotation. It can also open notes that were added by tasknote.",
  "url" : "https://github.com/ValiValpas/taskopen",
  "url_src" : "https://github.com/ValiValpas/taskopen",
  "license" : "GPLv2",
  "language" : [ ],
  "author" : [ "Johannes Schlatow" ],
  "theme" : [ ],
  "compatibility" : "2.4.0",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2014-02-14"
}, {
  "category" : "Extensions",
  "name" : "vimwiki-tasks",
  "description" : "A Vim plugin to integrate Vimwiki tasks with taskwarrior. Syncs tasks between vimwiki and taskwarrior in both directions.",
  "url" : "https://github.com/teranex/vimwiki-tasks",
  "url_src" : "https://github.com/teranex/vimwiki-tasks",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Jeroen Budts" ],
  "theme" : [ "Vim" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-12-01"
}, {
  "category" : "Extensions",
  "name" : "taskrambler",
  "description" : "Multi user task organization and management tool",
  "url" : "https://github.com/georghopp/taskrambler",
  "url_src" : "https://github.com/georghopp/taskrambler",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Georg Hopp" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-11-28"
}, {
  "category" : "Extensions",
  "name" : "taskquery",
  "description" : "A simply query interface for Taskwarrior. This script lets you on-the-fly specify which columns you want to see in a report and how the result should be sorted. When you just want to create a simple custom report which you are going to use once, this is much simpler then having to create a custom report, or specify all the rc-override on the commandline.",
  "url" : "https://github.com/teranex/taskquery",
  "url_src" : "https://github.com/teranex/taskquery",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Jeroen Budts" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-11-10"
}, {
  "category" : "Extensions",
  "name" : "trello_to_task",
  "description" : "Tool to migrate from \n<a href=\"http://trello.com\">Trello</a> to Taskwarrior",
  "url" : "https://github.com/jbarratt/trello_to_task",
  "url_src" : "https://github.com/jbarratt/trello_to_task",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Joshua Barratt" ],
  "theme" : [ ],
  "compatibility" : "2.0.0",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-09-18"
}, {
  "category" : "Extensions",
  "name" : "task-git.sh",
  "description" : "A wrapper around Taskwarrior that places the task database in version control, and generates commits each time the database is altered.",
  "url" : "https://github.com/kostajh/task-git",
  "url_src" : "https://github.com/kostajh/task-git",
  "license" : "GPLv3",
  "language" : [ ],
  "author" : [ "Kosta Harlan" ],
  "theme" : [ ],
  "compatibility" : "2.2.0",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-09-02"
}, {
  "category" : "Extensions",
  "name" : "twdeps",
  "description" : "Vizualizes dependencies between Taskwarrior tasks",
  "url" : "https://github.com/nerab/twdeps",
  "url_src" : "https://github.com/nerab/twdeps",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Nicholas E. Rabenau" ],
  "theme" : [ ],
  "compatibility" : "2.1.2",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-07-23"
}, {
  "category" : "Extensions",
  "name" : "taskwarrior-progress",
  "description" : "Progress Reports for Taskwarrior Projects",
  "url" : "https://github.com/frenchrd/taskwarrior-progress",
  "url_src" : "https://github.com/frenchrd/taskwarrior-progress",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Robert D. French" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-07-16"
}, {
  "category" : "Extensions",
  "name" : "taskboy",
  "description" : "Create a new note in Tomboy with individual tasks in Taskwarrior.",
  "url" : "https://github.com/pi3ch/taskboy",
  "url_src" : "https://github.com/pi3ch/taskboy",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Pedram Hayati" ],
  "theme" : [ ],
  "compatibility" : "1.9.4",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-07-03"
}, {
  "category" : "Extensions",
  "name" : "twoutline",
  "description" : "Taskwarrior to Outline",
  "url" : "https://github.com/AikidoGuy/twoutline",
  "url_src" : "https://github.com/AikidoGuy/twoutline",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Aikido Guy" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-06-21"
}, {
  "category" : "Extensions",
  "name" : "tw2latex",
  "description" : "Taskwarrior to LaTeX python utility",
  "url" : "https://github.com/AikidoGuy/tw2latex",
  "url_src" : "https://github.com/AikidoGuy/tw2latex",
  "license" : "Unknown",
  "language" : [ "Python" ],
  "author" : [ "Aikido Guy" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-06-21"
}, {
  "category" : "Extensions",
  "name" : "tasksync",
  "description" : "A tool for bidirectional synchronization of task repositories, like Taskwarrior and Google Tasks.",
  "url" : "https://github.com/burnison/tasksync",
  "url_src" : "https://github.com/burnison/tasksync",
  "license" : "GPLv3",
  "language" : [ ],
  "author" : [ "Richard Burnios" ],
  "theme" : [ ],
  "compatibility" : "2.1.1",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-05-29"
}, {
  "category" : "Extensions",
  "name" : "taskreport",
  "description" : "taskreport allows you to export a list of \"reports\" (these are just list of tasks defined by a filter rule) to HTML format, and then, print the HTML format to a file or send it by email. The html layout is customizable by the use of Jinja templates.",
  "url" : "http://pypi.python.org/pypi/taskreport",
  "url_src" : "https://pypi.python.org/pypi/taskreport",
  "license" : "GPLv3",
  "language" : [ ],
  "author" : [ "Alicia BEL & Thibaut HOREL" ],
  "theme" : [ "Mail" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-04-10"
}, {
  "category" : "Extensions",
  "name" : "taskwarrior-workflow",
  "description" : "Taskwarrior workflow for Alfred v2",
  "url" : "https://github.com/anazimok/taskwarrior-workflow",
  "url_src" : "https://github.com/anazimok/taskwarrior-workflow",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Alex Nazimok" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-04-08"
}, {
  "category" : "Extensions",
  "name" : "tb2taskwarrior",
  "description" : "tb2taskwarrior can add a task from email in Thunderbird to Taskwarrior.",
  "url" : "https://github.com/pi3ch/tb2taskwarrior",
  "url_src" : "https://github.com/pi3ch/tb2taskwarrior",
  "license" : "GPLv2",
  "language" : [ ],
  "author" : [ "Pedram Hyati" ],
  "theme" : [ "Mail" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-04-02"
}, {
  "category" : "Extensions",
  "name" : "task-autodelay.pl",
  "description" : "Automated task delay - a sophisticated script that can be used to add 10 days to the due date of any tasks.",
  "url" : "http://spiegl.de/andy/software/task-autodelay.pl",
  "url_src" : "http://spiegl.de/andy/software/task-autodelay.pl",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Andy Spiegl" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-03-26"
}, {
  "category" : "Extensions",
  "name" : "mail2taskwarrior",
  "description" : "Add a task to taskwarrior via email",
  "url" : "https://github.com/neingeist/mail2taskwarrior",
  "url_src" : "https://github.com/neingeist/mail2taskwarrior",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "neingeist" ],
  "theme" : [ "Mail" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-03-18"
}, {
  "category" : "Extensions",
  "name" : "kanban-warrior",
  "description" : "A python script supporting my kanban workflow for Task Warrior. \n<small><a href=\"http://joosten-industries.nl/blog/2013/03/07/kanban-warrior/\">Blog</a></small>",
  "url" : "https://github.com/keigezellig/kanbanwarrior",
  "url_src" : "https://github.com/keigezellig/kanbanwarrior",
  "license" : "THE APPRECIATION LICENSE\" (Revision 0xFF)",
  "language" : [ "Python" ],
  "author" : [ "M. Joosten" ],
  "theme" : [ ],
  "compatibility" : "2.1.2",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-03-14"
}, {
  "category" : "Extensions",
  "name" : "Tasky",
  "description" : "A Taskwarrior client that doesn't suck very much.",
  "url" : "https://github.com/jonsterling/Tasky",
  "url_src" : "https://github.com/jonsterling/Tasky",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Jonathan Sterling" ],
  "theme" : [ ],
  "compatibility" : "2.1.2",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-03-04"
}, {
  "category" : "Extensions",
  "name" : "taskjabb",
  "description" : "Taskwarrior to jabber interface",
  "url" : "https://github.com/qbit/taskjabb",
  "url_src" : "https://github.com/qbit/taskjabb",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "qbit" ],
  "theme" : [ ],
  "compatibility" : "2.1.1",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-03-02"
}, {
  "category" : "Extensions",
  "name" : "taskiwi",
  "description" : "A web-interface for taskwarrior",
  "url" : "https://github.com/fdev31/taskiwi",
  "url_src" : "https://github.com/fdev31/taskiwi",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "fdev31" ],
  "theme" : [ "Web" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-02-21"
}, {
  "category" : "Extensions",
  "name" : "git-task",
  "description" : "mini-issue tracker for git repositories, using Taskwarrior.",
  "url" : "https://github.com/proxypoke/git-task",
  "url_src" : "https://github.com/proxypoke/git-task",
  "license" : "Free",
  "language" : [ ],
  "author" : [ "proxypoke" ],
  "theme" : [ ],
  "compatibility" : "2.1.2",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-02-11"
}, {
  "category" : "Extensions",
  "name" : "mess2task",
  "description" : "For adding a message ID from a mutt mail directly to the most recently added task. This is useful in combination with taskopen and the muttjump scripts on this page.",
  "url" : "https://github.com/ValiValpas/taskopen/blob/master/scripts/mess2task",
  "url_src" : "https://github.com/ValiValpas/taskopen/blob/master/scripts/mess2task",
  "license" : "GPLv2",
  "language" : [ ],
  "author" : [ "Jostein Berntsen" ],
  "theme" : [ "Mail" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-02-05"
}, {
  "category" : "Extensions",
  "name" : "mess2task2",
  "description" : "For adding a message ID from a mutt mail to the clipboard in KDE, making it possible to add this as an annotation to any task.",
  "url" : "https://github.com/ValiValpas/taskopen/blob/master/scripts/mess2task2",
  "url_src" : "https://github.com/ValiValpas/taskopen/blob/master/scripts/mess2task2",
  "license" : "GPLv2",
  "language" : [ ],
  "author" : [ "Jostein Berntsen" ],
  "theme" : [ "Mail" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-02-05"
}, {
  "category" : "Extensions",
  "name" : "mutt2task",
  "description" : "For adding an email from mutt as a task. \n<small>See: <a href=\"http://blog.nixternal.com/category/gtd/\">blog article</a></small> \n<small><a href=\"https://gist.github.com/noqqe/6562350\">Alternative implementation</a></small>",
  "url" : "https://github.com/ValiValpas/taskopen/blob/master/scripts/mutt2task",
  "url_src" : "https://github.com/ValiValpas/taskopen/blob/master/scripts/mutt2task",
  "license" : "GPLv2",
  "language" : [ ],
  "author" : [ "Richard A. Johnson" ],
  "theme" : [ "Mail" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-02-05"
}, {
  "category" : "Extensions",
  "name" : "sublime-taskwarrior",
  "description" : "A plugin for Sublime Text 2 to view, modify and add tasks with Taskwarrior.",
  "url" : "https://github.com/kostajh/sublime-taskwarrior",
  "url_src" : "https://github.com/kostajh/sublime-taskwarrior",
  "license" : "MIT License",
  "language" : [ ],
  "author" : [ "Kosta Harlan" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-01-29"
}, {
  "category" : "Extensions",
  "name" : "taskwarrior-dropbox",
  "description" : "A quick script to take text file from Dropbox and to add it to Taskwarrior.",
  "url" : "https://github.com/mitnworb/taskwarrior-dropbox",
  "url_src" : "https://github.com/mitnworb/taskwarrior-dropbox",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Tim Brown" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-01-14"
}, {
  "category" : "Extensions",
  "name" : "graphdeps.py",
  "description" : "A Taskwarrior → GraphViz script that shows dependencies as a colorful graph. \n<small><a href=\"http://imgur.com/zipAg\">Sample</a></small>",
  "url" : "http://pastebin.com/9EyvEL0M",
  "url_src" : "http://pastebin.com/9EyvEL0M",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "mono_1" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2013-01-12"
}, {
  "category" : "Extensions",
  "name" : "rea",
  "description" : "Rea shows you the arithmetic mean time you have been active on a \n<em>recurring</em> task.",
  "url" : "https://raw.github.com/benjaminweb/scripts/master/rea",
  "url_src" : "https://raw.github.com/benjaminweb/scripts/master/rea",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "Benjamin Weber" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : null
}, {
  "category" : "Extensions",
  "name" : "xtw",
  "description" : "micro interface for Taskwarrior for OS X users",
  "url" : "https://github.com/tmcw/xtw",
  "url_src" : "https://github.com/tmcw/xtw",
  "license" : "own",
  "language" : [ ],
  "author" : [ "Tom MacWright" ],
  "theme" : [ "OSX" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-12-11"
}, {
  "category" : "Extensions",
  "name" : "taskpacifist",
  "description" : "A vim script for running Taskwarrior.",
  "url" : "https://github.com/Liberationtech/taskpacifist",
  "url_src" : "https://github.com/Liberationtech/taskpacifist",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Oivvio Polite" ],
  "theme" : [ "Vim" ],
  "compatibility" : "2.0.0",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-09-17"
}, {
  "category" : "Extensions",
  "name" : "AlfredTaskwarrior",
  "description" : "Alfred extension for integration with Taskwarrior.",
  "url" : "https://github.com/jbarratt/AlfredTaskwarrior",
  "url_src" : "https://github.com/jbarratt/AlfredTaskwarrior",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Joshua Barratt" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-09-05"
}, {
  "category" : "Extensions",
  "name" : "tasknote",
  "description" : "tasknote is used to associate a single textfile with a task. The note file is created automatically and uses the UUID for a filename, for uniqueness.",
  "url" : "https://github.com/mikebobroski/tasknote",
  "url_src" : "https://github.com/mikebobroski/tasknote",
  "license" : "GPLv2",
  "language" : [ ],
  "author" : [ "Alan Bowen", "Michael Bobroski", "BJoern Doebel" ],
  "theme" : [ ],
  "compatibility" : "2.2.0",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-08-30"
}, {
  "category" : "Extensions",
  "name" : "mamattd.plugins.taskwarrior",
  "description" : "A taskwarrior plugin for \n<a href=\"https://github.com/ralphbean/mattd.core\">mattd.code</a>",
  "url" : "https://github.com/ralphbean/mattd.plugins.taskwarrior",
  "url_src" : "https://github.com/ralphbean/mattd.plugins.taskwarrior",
  "license" : "GPLv3",
  "language" : [ ],
  "author" : [ "Matt Daemon" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-08-28"
}, {
  "category" : "Extensions",
  "name" : "taskchain",
  "description" : "taskchain is a script to create a single dependency chain from the input of task IDs.",
  "url" : "https://bug.tasktools.org/browse/EX-44",
  "url_src" : "https://bug.tasktools.org/browse/EX-44",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Scott Kostyshak (please contact with any problems or feature requests)" ],
  "theme" : [ ],
  "compatibility" : "1.9.3+",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-08-05"
}, {
  "category" : "Extensions",
  "name" : "TaskWarriorWeb",
  "description" : "A Yesod-based local web interface to TaskWarrior",
  "url" : "https://github.com/jonsterling/TaskWarriorWeb",
  "url_src" : "https://github.com/jonsterling/TaskWarriorWeb",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Jonathan Sterling" ],
  "theme" : [ "Web" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-05-02"
}, {
  "category" : "Extensions",
  "name" : "t",
  "description" : "'t' is a taskwarrior wrapper. It provides implicit project values on the command line, for adding and filtering, based on the current directory. \n<small><a href=\"https://bitbucket.org/ciberandy/t\">BiutBucket</a></small>",
  "url" : "http://spiegl.de/andy/software/t.tar.gz",
  "url_src" : "http://spiegl.de/andy/software/t.tar.gz",
  "license" : "MIT",
  "language" : [ ],
  "author" : [ "by Andy Spiegl" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-04-20"
}, {
  "category" : "Extensions",
  "name" : "taskattach",
  "description" : "Provides support for attachment management for Taskwarrior.",
  "url" : "https://github.com/tzok/taskattach",
  "url_src" : "https://github.com/tzok/taskattach",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Tomasz Żok" ],
  "theme" : [ ],
  "compatibility" : "1.9.4",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-04-19"
}, {
  "category" : "Extensions",
  "name" : "taskweb",
  "description" : "Simple PHP implementation to display tasks exported from Taskwarrior.",
  "url" : "https://github.com/erichschroeter/taskweb",
  "url_src" : "https://github.com/erichschroeter/taskweb",
  "license" : "Unknown",
  "language" : [ "PHP" ],
  "author" : [ "Erich Schroeter" ],
  "theme" : [ ],
  "compatibility" : "1.9.4",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-04-17"
}, {
  "category" : "Extensions",
  "name" : "taskmailer",
  "description" : "Email yourself status updates from Taskwarrior",
  "url" : "https://github.com/ajpierce/taskmailer",
  "url_src" : "https://github.com/ajpierce/taskmailer",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Andrew J. Pierce" ],
  "theme" : [ "Mail" ],
  "compatibility" : "1.9.4",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2012-03-05"
}, {
  "category" : "Extensions",
  "name" : "Taskwarrior XMPP Bot",
  "description" : "Taskwarrior XMPP (Jabber) Bot proof of concept written in Python",
  "url" : "https://gist.github.com/wbsch/4109562",
  "url_src" : "https://gist.github.com/wbsch/4109562",
  "license" : "Unknown",
  "language" : [ "Python" ],
  "author" : [ "Wim Schürmann" ],
  "theme" : [ ],
  "compatibility" : "*",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : null
}, {
  "category" : "Extensions",
  "name" : "local-task.sh",
  "description" : "local-task.sh is a script that provides directory-specific task databases. Read the script for detailed instructions on installation and usage.",
  "url" : "https://bug.tasktools.org/browse/TW-514",
  "url_src" : "https://bug.tasktools.org/browse/TW-514",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Wim Schuermann" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2011-12-11"
}, {
  "category" : "Extensions",
  "name" : "Dependency Trees",
  "description" : "Dependency trees for Taskwarrior",
  "url" : "https://github.com/iamnafets/taskwarrior_depends",
  "url_src" : "https://github.com/iamnafets/taskwarrior_depends",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Stefan Mai" ],
  "theme" : [ ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2011-11-17"
}, {
  "category" : "Extensions",
  "name" : "TextPuller",
  "description" : "Pulls in text from a text file online. \n<small><a href=\"http://www.schwertly.com/2011/05/dashboard-widget-for-taskwarrior-text-files/\">Blog</a></small>",
  "url" : "https://github.com/Stantheman/TextPuller",
  "url_src" : "https://github.com/Stantheman/TextPuller",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Stan Schwertly" ],
  "theme" : [ ],
  "compatibility" : "1.9.4",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2011-05-13"
}, {
  "category" : "Extensions",
  "name" : "muttjump",
  "description" : "For jumping to a specific mail in mutt via macro. This can be used together with taskopen to open a mutt message from a task.",
  "url" : "https://github.com/weisslj/muttjump",
  "url_src" : "https://github.com/weisslj/muttjump",
  "license" : "Unknown",
  "language" : [ ],
  "author" : [ "Johannes Weissl" ],
  "theme" : [ "Mail" ],
  "compatibility" : "Unknown",
  "obsolete" : false,
  "verified" : "2015-08-15",
  "last_update" : "2011-03-19"
} ]
