var tools = [
  {
    "category": "Front End",
    "name": "taskwarrior-pomodoro",
    "description": "taskwarrior-pomodoro is a simple application allowing you to use Pomodoro techniques with Taskwarrior on OSX.",
    "url": "https://github.com/coddingtonbear/taskwarrior-pomodoro",
    "url_src": "https://github.com/coddingtonbear/taskwarrior-pomodoro",
    "license": "Unknown",
    "author": ["Adam Coddington"],
    "compatibility": "2.0+",
      "language": ["C"],
    "OS": "OSX",
    "obsolete": false,
    "theme":["GUI", "TimeTracking", "Pomodoro"],
    "last_update": "2015-12-07",
    "verified": ""
  },
  {
    "category": "Service",
    "name": "FreeCinc",
    "description": "Don't want to manage your own Taskserver?  FreeCinc is a hosted implementation of Taskserver, where you can download a set of uniquely-generated credentials and start syncing for free.",
    "url": "http://freecinc.com",
    "url_src": "",
      "language": ["C"],
    "license": "Unknown",
    "author": ["Jack Desert"],
    "compatibility": "2.3.0+",
    "obsolete": false,
    "theme":["Syncing"],
    "last_update":"",
    "verified": "2015-08-15"
  },
    {
    "category": "Library",
    "name": "tasklib",
    "description": "Python library for interacting with Taskwarrior data.",
    "url": "http://tasklib.readthedocs.org/en/latest/",
    "url_src": "https://github.com/tbabej/tasklib",
    "license": "BSD 3 clause",
    "language": ["Python"],
    "author": ["Rob Golding", "Tomas Babej"],
    "compatibility": "2.1.x - 2.4.x",
    "theme":["Data"],
    "obsolete": false,
    "verified": "2015-08-15",
    "last_update": "2015-08-09"
  },
    {
        "category": "Extension",
        "name": "awesome-taskwarrior",
        "description": "Integrate TaskWarrior into the Awesome windows manager (WM).",
        "url": "https://github.com/ValiValpas/awesome-taskwarrior",
        "url_src": "",
        "license": "",
        "language": ["Lua"],
        "author": ["Johannes S."],
        "theme":["Integration", "WM"],
        "compatibility": "",
        "obsolete": true,
        "verified": "2015-08-15",
        "last_update": "2010-11-20"
    },
    {
        "category": "Front End",
        "name": "taskswamp",
        "description": "Taskswamp is a simple script to launch an xterm containing a tmux containing multiple task reports, and have them refreshed at a keypress.",
        "url": "https://github.com/danielshahaf/taskswamp/",
        "url_src": "",
        "license": "Apache 2.0",
        "language": ["Python"],
        "author": ["Daniel Shahaf"],
        "theme":["Report", "tmux"],
        "compatibility": "Any",
        "obsolete": false,
        "verified": "2015-08-15",
        "last_update": "2015-08-12"
    }
  ]
